### ISSUE TITLE
Create a grid

### ISSUE THREAD

**Issue by Eli-Jagnow** [Eli-Jagnow/LogicGridPuzzle#5]
We should set up a grid for one puzzle first, then look at the basics to frame the capability of creating many different varieties of grids in the future.

![image](https://user-images.githubusercontent.com/32276612/41630064-9a190f56-73f2-11e8-9dbb-2f2a87775d14.png)

**Comment by danjagnow** [comment]
The website is using [Bootstrap](https://getbootstrap.com/docs/3.3/) as a framework for styling.  The [Bootstrap tables](https://getbootstrap.com/docs/3.3/css/#tables) probably don't support our needs very well, so we'll need to write some custom CSS.  You can find some information about that [here](https://css-tricks.com/complete-guide-table-element/).

**Comment by danjagnow** [comment]
Resolved with PR #6.
